### PR TITLE
ImGui Font Scaling

### PR DESCRIPTION
**Pull request by anchorlightforge**
Some users requested the ability to scale the UI and after a brief investigation, it seems this may actually be doable.  Attached to this PR is two commits.  One can be ignored as it's purely for my own testing purposes.  The other is a commit that:
- Adds a new RTX Option for font scale
- Adds a slider to adjust said font scale option [placeholder]
- Multiplies the font size during font creation

This approach has some drawbacks.  
- At the moment the font scale adjustment requires a restart.  Attempting to create a new font during runtime results in a crash with the current implementation, which just repeats the font creation step from startup... but there may be better alternatives to refreshing the font.  I have some ideas for how to get around this but it'll take some investigation and testing.
- This has only been applied to fonts; I will also need to add the variable to various existing ImGui elements with hardcoded values (e.g. the Remix splash message).  I will be further investigating this over the next week to see about adding a more polished version of this option to the menus.  I would also like some advice on where a UI-specific setting should be placed as most options in the Remix menu either pertain to a specific tab/section or the game settings, not the menu settings.

borderzone_llHEsV6qCi
borderzone_0NrqbagOx0

### CODE REVIEW

**Comment by NV-DM** [comment]
REMIX-2376 for tracking.

**Comment by pkristof** [comment]
Is this still meant to be in Draft state?

**Comment by anchorlightforge** [comment]
Yes, at the moment the code needs some refactoring and I'm still
investigating how to scale the fonts during runtime as well as how best to
provide user options for this.  There's also a few UI elements that need
scaling with it.

I've been meaning to get back to it but I won't have a day to do so until
tomorrow and Friday. Sorry for the delay!

**Comment by anchorlightforge** [comment]
Yes, I meant to get back to it a few weeks ago but got held up by some personal issues.  I apologize for the delay but I plan on looking into this tomorrow and Friday to get it ready for review.

**Comment by anchorlightforge** [comment]
Branch is stale-- I haven't had as much time as of late to work on this ticket so I will shelve this for now and re-implement it in the future.  I apologize for the added delay.

**Pull request closed without merging**
