### PR TITLE
Fixed bug where user can't select some resolutions in game

### PR DESCRIPTION
**Pull request by sortifal**
Fixed a bug where resolutions could'nt be set properly on high resolutions. Set back omni material dependecy version back to 11 to be build compliant.

### CODE REVIEW

**Comment by xoxor4d** [comment]
fyi (nv) - this is already integrated into dxvk: https://github.com/doitsujin/dxvk/issues/3214

**Comment by nvzkupu** [comment]
There was an issue with version 12 of `rtx-remix-omni_core_materials` not being publicly available. We have since resolved the temporary issue and this change should no longer be required. 

@sortifal Please test with version 12 of `rtx-remix-omni_core_materials` again and let us know if the problem selecting some resolutions remains.

**Comment by sortifal** [comment]
> There was an issue with version 12 of `rtx-remix-omni_core_materials` not being publicly available. We have since resolved the temporary issue and this change should no longer be required. 
> 
> 
> 
> @sortifal Please test with version 12 of `rtx-remix-omni_core_materials` again and let us know if the problem selecting some resolutions remains. 

The v12 of 'rtx-remix-omni_core_materials' now compile properly but the resolutions problem is still here. Do you want me to make a new PR with v12 ?

**Comment by nvzkupu** [comment]
@sortifal No, you can keep this PR in place, just modify the configs to pull v12 of `rtx-remix-omni_core_materials`.

Thank you for confirming and verifying that the resolution issue is still present, even with v12.

**Comment by sortifal** [comment]
> @sortifal No, you can keep this PR in place, just modify the configs to pull v12 of `rtx-remix-omni_core_materials`.
> 
> Thank you for confirming and verifying that the resolution issue is still present, even with v12.

I know pushed a fix with v12 of `rtx-remix-omni_core_materials`. I confirm that the problem was still there with v12 (tested on call of duty 2) and is fixed with the things I changed.

**Comment by AlexDunn** [comment]
@sortifal thank you for putting this PR together.

I noticed that this fix is a squashed version of the upstream fix from DXVK (commits below).  Would it be possible to cherrypick those commits directly?  This will greatly help us when it comes time to merge upstream DXVK into Remix.

Also please add yourself as a contributer to the credits (see `ImGuiAbout::Credits::Credits()`) in a separate commit.

https://github.com/doitsujin/dxvk/commit/1568c263fbec4c8d5f8f9286e0be40af7fdfb9a6
https://github.com/doitsujin/dxvk/commit/0cd4165658537405d84a43f3ab6180b770f30fe1
https://github.com/doitsujin/dxvk/commit/4b8e8bed6e7007144f803ec64485168c82273c6f

**Comment by NV-LL** [comment]
REMIX-3065 for tracking

**Comment by sortifal** [comment]
I know it's been a while but I added myself as contributor as you said so

**Comment by MarkEHenderson** [comment]
> I know it's been a while but I added myself as contributor as you said so

I know it's been a while, but it looks like you did some kind of auto formatting on the entire file when you added yourself as a contributor.  Could you please revert those changes, and redo that commit with just adding your name?

**Comment by MarkEHenderson** [comment]
This PR has been merged as of action build number 641:
https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/10821103602
Thanks for the contribution, and sorry it took us a while to bring it in.

**Pull request closed without merging**
