### PR TITLE
Add option to configure the scene world space coordinate system

### PR DESCRIPTION
**Pull request by jdswebb**
## Description

Fixes https://github.com/NVIDIAGameWorks/rtx-remix/issues/432.

`SceneManager::calculateSceneRight()` assumed a right-handed coordinate system, which meant it computed the wrong value for games using a left-handed coordinate system.

This change adds an option `leftHandedCoordinateSystem` which makes the world space coordinate system configurable. I have exposed this option on the developer GUI alongside the `zUp` option.

## Testing

Tested in Star Wars Galaxies which uses a left-handed coordinate system. The terrain baking previously failed due to the incorrect value computed by `SceneManager::calculateSceneRight()`:

image

Now works with the option enabled:

image

### CODE REVIEW

**Comment by xbei-nv** [comment]
Everything looks good. Could you also squash your changes in a separate branch and force push the squashed commit to this topic branch?

**Comment by jdswebb** [comment]
> Everything looks good. Could you also squash your changes in a separate branch and force push the squashed commit to this topic branch?

Sure, I didn't do that already as I assumed you would just use the Github squash/merge. Is the problem that you don't want the verbose description? If so shall I just title the squashed commit with the title of this PR?

**Comment by jdswebb** [comment]
> > Everything looks good. Could you also squash your changes in a separate branch and force push the squashed commit to this topic branch?
> 
> Sure, I didn't do that already as I assumed you would just use the Github squash/merge. Is the problem that you don't want the verbose description of the PR becoming the commit message? If so shall I just title the squashed commit with the title of this PR?

I went ahead and did it this way, but if you wanted something else just let me know.

**Comment by xbei-nv** [comment]
> > Everything looks good. Could you also squash your changes in a separate branch and force push the squashed commit to this topic branch?
> 
> Sure, I didn't do that already as I assumed you would just use the Github squash/merge. Is the problem that you don't want the verbose description of the PR becoming the commit message? If so shall I just title the squashed commit with the title of this PR?

The reason is we want to keep your name on the commit, because I need to cherry-pick your change and run some tests then merge here. If I squash on my side, the final merge submit will under my name which is not good. At the same time, we also want to keep the commit history clean so something like "Minor fixes" will not appear in the history.

**Comment by xbei-nv** [comment]
> > > Everything looks good. Could you also squash your changes in a separate branch and force push the squashed commit to this topic branch?
> > 
> > 
> > Sure, I didn't do that already as I assumed you would just use the Github squash/merge. Is the problem that you don't want the verbose description of the PR becoming the commit message? If so shall I just title the squashed commit with the title of this PR?
> 
> I went ahead and did it this way, but if you wanted something else just let me know.

OK thanks a lot!

**Comment by xbei-nv** [comment]
We have started tests, will let you know as soon as it gets merged

**Comment by xbei-nv** [comment]
Passed internal tests and merged.

**Comment by PappaSlask** [comment]
Hi. I'm project lead on Max Payne Remixed.

The capture Left-handed setting has no effect in Max Payne, it used to work before, last summer. But it hasn't been working for quite some time now. Can you please look into it @jdswebb ? If there's a simple fix, I would very much want to learn about it, rather than waiting until the next big Remix update.

I posted a report about this on the combined issues page, but I wasn't able to tag you for a comment James.
https://github.com/NVIDIAGameWorks/rtx-remix/issues/494

I can provide any files needed for troubleshooting. On behalf of my team and myself, assistance would be highly appreciated! Thank you!

**Pull request closed without merging**
